import {
    House, 
    Medal, 
    Sprout, 
    Plus, 
    Sparkle, 
    Bell, 
    Flower,
    Receipt, 
    ArrowLeft, 
    Trash, 
    Shield,
    CircleUserRound, 
    GlobeLock, 
    Palette, 
    HandCoins, 
    CircleDollarSign, 
    Wallet, 
    BadgeInfo, 
    CircleQuestionMark,
    Settings,
    Funnel,
    Search,
    ChevronDown,
    ChevronRight,
    ChevronUp,
    LogOut,
    Gamepad2,
    Apple,
    Coffee,
    PawPrint,
    Clapperboard,
    Banknote,
    Shirt,
    HeartPulse,
    Car,
    Coins,
    Handbag,
    Wine,
    Headset,
    Music,
    Dumbbell,
    LibraryBig,
    Bubbles,
    Volleyball,
    Plane,
    Sofa,
    Circle,
    Flame,
    Check,
    CalendarDays,
    Leaf,
    Zap,
    Tags,
    Sparkles,
    Gift,
    BriefcaseBusiness,
    Brush,
    UndoDot,
    Target,
    Pencil,
    Gem,
    PiggyBank,
    Heart,
    ArrowUp,
    X,
    MessageCircle,
    Eye,
    EyeClosed,
    GraduationCap,
    Store,
    Phone,
    Tv,
    Paintbrush,
    PenTool,
    Baby,
    KeySquare,
    Rabbit,
    Bird,
    Cat,
    Dog,
    Fish,
    FerrisWheel,
    Bot,
    Popcorn,
    Flower2,
    Drama,
    Dices,
    Club,
    BedDouble,
    Lamp,
    CircleParking,
    MicVocal,
    Recycle,
    WavesLadder,
    Tent,
    Wrench,
    CheckLine,
    Move
} from "lucide-react"

export const appIcons = {
    // UI icons
    visible: Eye,
    hidden: EyeClosed,
    checkLine: CheckLine,
    home: House,
    transactions: Receipt,
    add: Plus,
    goals: Banknote,
    profile: Sparkle,
    notifications: Bell,
    settings: Settings,
    back: ArrowLeft,
    up: ArrowUp,
    close: X,
    chat: MessageCircle,
    account: CircleUserRound,
    delete: Trash,
    dataPrivacy: GlobeLock,
    theme: Palette,
    monthlyBudget: HandCoins,
    currency: CircleDollarSign,
    customSpendingRules: Wallet,
    appTips: BadgeInfo,
    faq: CircleQuestionMark,
    topCategory: Medal,
    primaryGoal: Sprout,
    search: Search,
    filter: Funnel,
    select: ChevronDown,
    seeDetails: ChevronRight,
    hideDetails: ChevronUp,
    categories: Flower,
    privacyPolicy: Shield,
    streak: Flame,
    completed: Check,
    logOut: LogOut,
    calendar: CalendarDays,
    leaf: Leaf,
    zap: Zap,
    tags: Tags,
    sparkles: Sparkles,
    edit: Pencil,
    move: Move,
    piggyBank: PiggyBank,
    heart: Heart,

    // category icons
    gamepad2: Gamepad2,
    coffee: Coffee,
    pawprint: PawPrint,
    shirt: Shirt,
    heartPulse: HeartPulse,
    car: Car,
    apple: Apple,
    coins: Coins,
    handbag: Handbag,
    clapperboard: Clapperboard,
    wine: Wine,
    headset: Headset,
    bubbles: Bubbles,
    music: Music,
    dumbbell: Dumbbell,
    libraryBig: LibraryBig,
    volleyball: Volleyball,
    plane: Plane,
    sofa: Sofa,
    banknote: Banknote,
    gift: Gift,
    briefcase: BriefcaseBusiness,
    brush: Brush,
    refund: UndoDot,
    target: Target,
    gem: Gem,
    graduationCap: GraduationCap,
    store: Store,
    phone: Phone,
    tv: Tv,
    paintbrush: Paintbrush,
    pen: PenTool,
    baby: Baby,
    keySquare: KeySquare,
    rabbit: Rabbit,
    bird: Bird,
    cat: Cat,
    dog: Dog,
    fish: Fish,
    ferrisWheel: FerrisWheel,
    bot: Bot,
    popcorn: Popcorn,
    flower2: Flower2,
    drama: Drama,
    dices: Dices,
    club: Club,
    bed: BedDouble,
    lamp: Lamp,
    parking: CircleParking,
    mic: MicVocal,
    recycle: Recycle,
    swimming: WavesLadder,
    tent: Tent,
    wrench: Wrench,
    circle: Circle
}

export const CUSTOM_CATEGORY_KEYS = [
    "graduationCap", "store", "phone", "tv", "paintbrush", "pen",
    "baby", "keySquare", "rabbit", "bird", "cat", "dog", "fish", "ferrisWheel",
    "bot", "popcorn", "flower2", "drama", "dices", "club", "bed", "lamp", "coffee",
    "dumbbell", "gamepad2", "pawprint", "shirt", "wine", "headset", "bubbles",
    "music", "libraryBig", "volleyball", "plane", "sofa", "parking", "mic",
    "recycle", "swimming", "tent", "wrench"
]