import {
    House, 
    Medal, 
    Sprout, 
    Plus, 
    Sparkle, 
    Bell, 
    Flower,
    Receipt, 
    ArrowLeft, 
    Trash, 
    Shield,
    CircleUserRound, 
    GlobeLock, 
    Palette, 
    HandCoins, 
    CircleDollarSign, 
    Wallet, 
    BadgeInfo, 
    CircleQuestionMark,
    Settings,
    Funnel,
    Search,
    ChevronDown,
    ChevronRight,
    ChevronUp,
    LogOut,
    Gamepad2,
    Apple,
    Coffee,
    PawPrint,
    Clapperboard,
    Banknote,
    Shirt,
    HeartPulse,
    Car,
    Coins,
    Handbag,
    Wine,
    Headset,
    Music,
    Dumbbell,
    LibraryBig,
    Bubbles,
    Volleyball,
    Plane,
    Sofa,
    Circle,
    Flame,
    Check,
    CalendarDays,
    Leaf,
    Zap,
    Tags,
    Sparkles,
    Gift,
    BriefcaseBusiness,
    Brush,
    UndoDot
} from "lucide-react"

export const appIcons = {
    // UI icons
    home: House,
    transactions: Receipt,
    add: Plus,
    goals: Banknote,
    profile: Sparkle,
    notifications: Bell,
    settings: Settings,
    back: ArrowLeft,
    account: CircleUserRound,
    delete: Trash,
    dataPrivacy: GlobeLock,
    theme: Palette,
    monthlyBudget: HandCoins,
    currency: CircleDollarSign,
    customSpendingRules: Wallet,
    appTips: BadgeInfo,
    faq: CircleQuestionMark,
    topCategory: Medal,
    primaryGoal: Sprout,
    search: Search,
    filter: Funnel,
    select: ChevronDown,
    seeDetails: ChevronRight,
    hideDetails: ChevronUp,
    categories: Flower,
    privacyPolicy: Shield,
    streak: Flame,
    completed: Check,
    logOut: LogOut,
    calendar: CalendarDays,
    leaf: Leaf,
    zap: Zap,
    tags: Tags,
    sparkles: Sparkles,

    // category icons
    gamepad2: Gamepad2,
    coffee: Coffee,
    pawprint: PawPrint,
    shirt: Shirt,
    heartPulse: HeartPulse,
    car: Car,
    apple: Apple,
    coins: Coins,
    handbag: Handbag,
    clapperboard: Clapperboard,
    wine: Wine,
    headset: Headset,
    bubbles: Bubbles,
    music: Music,
    dumbbell: Dumbbell,
    libraryBig: LibraryBig,
    volleyball: Volleyball,
    plane: Plane,
    sofa: Sofa,
    banknote: Banknote,
    gift: Gift,
    briefcase: BriefcaseBusiness,
    brush: Brush,
    refund: UndoDot,
    circle: Circle
}