import {
    Gamepad2,
    Apple,
    Coffee,
    PawPrint,
    Clapperboard,
    Banknote,
    Shirt,
    HeartPulse,
    Car,
    Coins,
    Handbag,
    Wine,
    Headset,
    Music,
    Dumbbell,
    LibraryBig,
    Bubbles,
    Volleyball,
    Plane,
    Sofa,
    Circle
} from "lucide-react"

export const categoryIcons = {
    gamepad2: Gamepad2,
    coffee: Coffee,
    pawprint: PawPrint,
    shirt: Shirt,
    heartPulse: HeartPulse,
    car: Car,
    apple: Apple,
    coins: Coins,
    handbag: Handbag,
    clapperboard: Clapperboard,
    wine: Wine,
    headset: Headset,
    bubbles: Bubbles,
    music: Music,
    dumbbell: Dumbbell,
    libraryBig: LibraryBig,
    volleyball: Volleyball,
    plane: Plane,
    sofa: Sofa,
    banknote: Banknote,
    circle: Circle
}